CC = gcc

mkfile_path := $(abspath $(lastword $(MAKEFILE_LIST)))
mkconfig_dir := $(dir $(mkfile_path))
KERNEL_INCLUDE := -I$(mkconfig_dir)include
LIBC_INCLUDE :=  -I$(mkconfig_dir)libc/include

DEBUG = -ggdb
CFLAGS = -m32 -nostdlib -nostdinc -fno-builtin -fno-stack-protector \
	 -nostartfiles -nodefaultlibs -D__KERNEL_MOD $(LIBC_INCLUDE) $(KERNEL_INCLUDE) -Wall -Wextra -Werror $(DEBUG) -c
AS = nasm
ASFLAGS = -f elf32


# to-do
# function for testing verification of multi-boot
